withpet/urls.py
from django.contrib import admin
from django.urls import path
import blog.views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name='home'),
    path('comment_write/<int:post_pk>/', blog.views.comment_write, name="comment_write" ),
    path('delete/<int:post_id>', blog.views.delete, name = 'delete'),
    path('delete1/<int:post_id>/<int:comment_id>', blog.views.delete1, name = 'delete1'),
    path('post/<int:post_id>', blog.views.post, name = 'post'),
    path('post/<pk>/likes/', blog.views.like, name = 'likes'),
    path('modify/<int:post_id>', blog.views.modify, name='modify'),
    path('new/', blog.views.new, name = "new"),
    path('accounts/',include('accounts.urls')),
    path('detail/', blog.views.detail, name = "detail"),

] 
urlpatterns+=static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    writer = models.ForeignKey(User, editable =False, null=True, blank=True, on_delete=models.SET_NULL,)
    title=models.CharField(max_length=200)
    place_thing = (('서울', '서울'), ('경기', '경기'), ('강원', '강원'),)
    place = models.CharField(max_length=3, choices=place_thing, default='서울',)
    type_thing = (('카페', '카페'), ('식당', '식당'), ('산책', '산책'),)
    placetype = models.CharField(max_length=3, choices=type_thing, default='카페',)
    date = models.DateTimeField(auto_now_add=True)
    explain = models.TextField(default='')
    image = models.ImageField(upload_to='images/', blank=True)
    menupicture = models.ImageField(upload_to='images/', blank=True)
    menutext = models.TextField(default='')

    def __str__(self):
        return self.title
    
    def summary(self):
        return self.content[:100]

class BlogLike(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Comment(models.Model):
    post_key = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, related_name='comments')
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_contents = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.comment_contents
        

blog/views.py
from .models import Blog, Comment, BlogLike
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.models import User
from .form import Postform
from django.contrib import auth
from django.contrib.auth.decorators import login_required

@login_required
def comment_write(request, post_pk):
    if request.method == 'POST':
        post = get_object_or_404(Blog, pk=post_pk)
        content = request.POST.get('content')
        if not content:
            messages.info(request, "You dont write anything...")
            return redirect('/post/' + str(post_pk))

        Comment.objects.create(post_key = post, comment_contents=content, author=request.user)
        return redirect('/post/'+str(post_pk))

def delete1(request, comment_id, post_id):
    comment = get_object_or_404(Comment , pk = comment_id )
    comment.delete()
    return redirect('/post/'+str(post_id))


@login_required
def delete(request, post_id):
    post = get_object_or_404(Blog, pk = post_id)
    post.delete()
    return redirect('detail')

def post(request, post_id):
    post_detail = get_object_or_404(Blog, pk=post_id)
    if request.user.is_authenticated:
        user = User.objects.get(username = request.user.get_username())
        return render(request, 'post.html', {'post':post_detail, 'user':user, 'post_id': post_detail.pk})
    else:
        return render(request, 'post.html', {'post':post_detail, 'post_id': post_detail.pk})


@login_required
def modify(request, post_id):
    post = get_object_or_404(Blog, pk = post_id)
    if request.method == "POST":
        form = Postform(request.POST, instance = post)
        if form.is_valid():
            post = form.save(commit=False)
            post.date = timezone.now()
            post.save()
            return redirect('post', post_id=post.pk)
    else:
        form = Postform(instance = post)
    return render(request, 'modify.html', {'form' : form, 'post_id':post.pk})

# def modify(request, post_id):
#     post = Blog.objects.get(id=post_id)
#     if request.method == 'POST':
#         form = Postform(request.POST, request.FILES)
#         if form.is_valid():
#             post.title = form.cleaned_data['title']   
#             post.content = form.cleaned_data['explain']
#             post.save()
#             return redirect('/post/' +str(post_id))
#     else:
#         form= Postform(instance=post)
#         return render(request,'modify.html',{'form':form})

@login_required
def new(request):
    if request.method == 'POST':
        form = Postform(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit = False)
            blog.writer=request.user
            blog.date = timezone.now()
            blog.save()
            return redirect('post', post_id=blog.pk)
    else :
        form = Postform()
        
    return render(request, 'new.html', {'form' : form})

def signup(request):
    if request.method == 'POST':
        if request.POST ['password1'] == request.POST['password2']:
            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error': 'Username has already been taken'})
            except User.DoesNotExist:
              user = User.objects.create_user(
              request.POST['username'], password = request.POST['password1'])
              auth.login (request,user)
            return redirect('home')
        else:
            return render (request, 'accounts/signup.html', {'eror': 'Passwords must match'})
    else:
        return render(request,'signup.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('home')
        else:
            return render (request, 'login.html', {'error':'username or password is incorrect.'})
    else:
        return render (request,'login.html')

def home(request):

    return render(request, 'home.html')

def detail(request):
    posts = Blog.objects.all()
    return render(request, 'detail.html', {'posts_list':posts})

@login_required
def like(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if BlogLike.objects.filter(blog=blog, user=request.user).count() == 0:
        BlogLike.objects.create(blog=blog, user=request.user)
    return redirect('post', post_id=pk)

# def search(request):
#     options = []
#     return render(request,'blog/detail.html', {'options':options})

# def result(request):
#     if request.method =="GET":
#         keyword1 = request.GET.get('keyword1')
#         keyword2 = request.GET.get('keyword2')
#         if ((keyword1 is not None) and (keyword2 is not None)):
#             posts = Blog.objects.filter(Q(find_place__icontains=keyword1) & Q(item_type__icontains=keyword2))
#             paginator = Paginator(posts, 3)
#             page = request.GET.get('page')
#             post_page = paginator.get_page(page)
#             return render(request, 'blog/detail.html', {'posts': posts, 'post_page': post_page, 'keyword1':keyword1, 'keyword2':keyword2}) 
#         else:
#             return render(request,'blog/detail.html')
#     else:
#         return render(request,'blog/detail.html')

blog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <link rel="stylesheet" href="style.css">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        * {
          background-color:#EFE3BB;
        }
    .navbar{
        background-color:#8ECDC5;
        height:100px;
    }
    .navbar-brand{
        font-size:50px;
        padding-left:10px;
    }
    
    </style>
    </head>

    <body>
            <nav class="navbar navbar-expand-lg">
                    <a class="navbar-brand" href="{% url 'home'%}">With Pet</a>
        
                    <img src='{%static "blog/image/baidu.png"%}' style="height: 65px; background-color:#8ECDC5">
                    
                    <span class="navbar-text">
                          </span>
                    </div>
            </nav>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/detail.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<head>
<link rel='stylesheet' type='text/css' href='{% static "blog/css/detail.css"%}'>
    <style>
        body {
            background-color: #EFE3BB;
            margin: 0 auto;
        }
    </style>
</head>

<body>
 <!-- Home Search -->
   <div class="home_search">
       <div class="container">
           <div class="row">
               <div class="col">
                   <div class="home_search_container">
                       <div class="home_search_content">
                           <form action="#" class="search_form d-flex flex-row align-items-center justify-content-center">
                               <div class="search_form_content d-flex flex-row align-items-center justify-content-center flex-wrap">
                                   <div>
                                       <select class="search_form_select">
                                           <option disabled selected>위치</option>
                                           <option> 서울 </option>
                                           <option> 인천 </option>
                                           <option> 경기 </option>
                                           <option> 강원 </option>
                                       </select>
                                   </div>
                                   <br>
                                   <div>
                                       <select class="search_form_select">
                                           <option disabled selected>갈 곳</option>
                                           <option> 식당 </option>
                                           <option> 카페 </option>
                                           <option> 산책로 </option>
                                           <option> 공원 </option>
                                       </select>
                                   </div>
                                   
                               </div>
                               
                                       
                               <button type="button" button class="btn ml-auto btn-info mt-1">search</button>
                               <a class="btn btn-info ml-2 mt-1" href = "{% url 'new' %}"> 글쓰기</a>
                           </form>
                           
                               
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>

      <!-- Recent -->

   <div class="recent">
      <div class="container">
         <div class="row">
            <div class="col">
            </div>
         </div>
         <div class="row recent_row">
            <div class="col">
               <div class="recent_slider_container">
                  <div class="owl-carousel owl-theme recent_slider">
                            
                            <div class="btn-group" role="group" aria-label="Basic example">
                                {% if post_page.has_previous %}
                                <a href="?keyword1={{keyword1}}&keyword2={{keyword2}}&page=1" class="btn btn-secondary">First</a>
                                <a href="?keyword1={{keyword1}}&keyword2={{keyword2}}&page={{post_page.previous_page_number}}" class="btn btn-secondary">Previous</a>
                                {% endif %}
                                {% if post_page.has_next %}
                                <a href="?keyword1={{keyword1}}&keyword2={{keyword2}}&page={{post_page.next_page_number}}" class="btn btn-secondary">Next</a>
                                <a href="?keyword1={{keyword1}}&keyword2={{keyword2}}&page={{post_page.paginator.num_pages}}" class="btn btn-secondary">Last</a>
                                {% endif %}
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    
    
{% for post in posts_list %}
<div class='jane' style='text-align:center;'>
    
<hr>
    <p>제목 : {{post.title}} </p>
    <p>내용 : {{post.explain}}</p>
    {% if post.image %}

    <img src="{{post.image.url}}" height=200>

    {%endif%}
    {% if post.menupicture %}
    <img src="{{post.menupicture.url}}" height=200>
    {%endif%}
    <br><br>
    <p>메뉴 : {{post.menutext}}</p>
    <p>지역 : {{post.place}}</p>
    <p>종류 : {{post.placetype}}</p>

    <a href = "{% url 'post' post.id%}">post게시글로 가기</a>

</div>
{% endfor %}

</body>
{% endblock %}

blog/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<style>
    @font-face { font-family: 'BBTreeGR'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_nine_@1.1/BBTreeGR.woff') format('woff'); font-weight: normal; font-style: normal; }
    @font-face { font-family: 'Arita-dotum-Medium'; src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_one@1.0/Arita-dotum-Medium.woff') format('woff'); font-weight: normal; font-style: normal; }

body {
    margin: 100px 500px;
    font-family : 'Arita-dotum-Medium';
    background-repeat:no-repeat;
    background-position : 65% 70%;
}

</style>

</head>

<body style="display: flex;">
<div class="main">
<h3> blog</h3>
<br><br>
  <div class="navbar">
    {% if user.is_authenticated %}
      환영합니다. {{user.username}} 님!!
    <a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}">로그아웃</a>
      <form id="logout" method="POST" action="{% url 'logout' %}">
      {% csrf_token %} <input type="hidden">
      </form>
    {% else %}
    <a class="nav-item nav-link" href="{% url 'signup' %}"> 회원가입</a>
    <br>
    <a class="nav-item nav-link" href="{% url 'login' %}">로그인</a>
    {% endif %}

  </div>

<a href = "{% url 'new' %}"> 글쓰기</a>
</div>
</body>

blog/templates/modify.html
{% extends 'base.html' %}

{% block content %}
        <div class="container-fluid py-5">
        <form method="POST">
                {% csrf_token %}
                <table>
                {{form.as_table}}
                </table>
        <br>
        <input type="submit" value="제출하기" >
        </form>
        <a href="{% url 'home' %}">돌아가기</a>
        </div>
</form>  

{% comment %} 
{% for post in posts_list %}

    <p>제목 : {{post.title}} </p>
    <p>내용 : {{post.explain}}</p>
    {% if post.image %}

    <img src="{{post.image.url}}" height=200>

    {%endif%}
    {% if post.menupicture %}
    <img src="{{post.menupicture.url}}" height=200>
    {%endif%}
    <p>메뉴 : {{post.menutext}}</p>
    <p>지역 : {{post.place}}</p>
    <p>종류 : {{post.placetype}}</p>
{% endfor %} {% endcomment %}
{% endblock %}

blog/templates/new.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<link rel='stylesheet' type='text/css' href='{% static "blog/css/new.css"%}'>

<center>
<div class="new-form py-5">
<h1 id="title1" style="margin:0;">새로운 글</h1>

<!-- <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Save</button>
</form> -->

<form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    <p class='title pt-5'>
        <input type="text" name="title" maxlength="200" required="" id="id_title" class="form-control col-6" placeholder="제목">
    </p>
    <div class="row col-6 p-0 text-left">
    <p class="col-6 pl-0"><label for="id_place" style="font-weight: 700;">장소</label> <select name="place" id="id_place" class="form-control">
  <option value="서울" selected="">서울</option>
  <option value="경기">경기</option>
  <option value="강원">강원</option>

</select></p>
<p class="col-6 pr-0"><label for="id_placetype" style="font-weight: 700;">장소종류</label> <select name="placetype" id="id_placetype" class="form-control ">
  <option value="카페" selected="">카페</option>
  <option value="식당">식당</option>
  <option value="산책">산책</option>

</select></p>
</div>
<p><textarea class="form-control col-6" name="explain" cols="40" rows="10" required="" id="id_explain" placeholder="설명"></textarea></p>
<div class="row col-6 p-0 text-left">
<p class="col-6 pl-0"><label for="id_image" style="font-weight: 700;">사진</label> <input class="form-control" type="file" name="image" accept="image/*" id="id_image"></p>
<p class="col-6 pr-0"><label for="id_menupicture" style="font-weight: 700;">메뉴판</label> <input class="form-control" type="file" name="menupicture" accept="image/*" id="id_menupicture"></p>
</div>
<p> <textarea placeholder="메뉴설명" class="form-control col-6" name="menutext" cols="40" rows="10" required="" id="id_menutext"></textarea></p>
    <button type="submit" class="btn btn-info btn-block col-6">등록</button>
</form>
</div>


</center>
{% endblock %}

blog/templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel='stylesheet' type='text/css' href='{% static "blog/css/post.css"%}'>

<div id="container-fluid" style=" padding-left : 200px; padding-top : 100px;" >
  <div class="row">
    <div class="col">



        <strong><p>제목 : {{post.title}} </p></strong>
        <p>내용 : {{post.explain}}</p>
        {% if post.image %}
        <img src="{{post.image.url}}" weight = 150 height=200>
        <br><br>
        {%endif%}
        <p>메뉴 : {{post.menutext}}</p>
        {% if post.menupicture %}
        <img src="{{post.menupicture.url}}" weight = 100 height=200>
        {%endif%}
        <p>지역 : {{post.place}}</p>

        <p>종류 : {{post.placetype}}</p>
        <p>좋아요 : {{ post.bloglike_set.count }}개</p>
        <a class="btn btn-info" href="{% url 'likes' pk=post.pk %}">좋아요</a>

    {% if post.writer == user %}
    <a href = "{% url 'modify' post_id=post_id %}">수정하기</a>
    <a href = "{% url 'delete' post_id=post_id %}" onclick="return confirm('정말 삭제하시겠습니까?')">삭제하기</a>
    {% endif %}

    </div>
    <div class="col">


<div style="overflow:scroll; width:400px; height:700px; padding:10px; background-color:#8ECDC5;">
<align right >
    {% for comment in post.comments.all %}
    <div class="comment">
        <div class="date">{{comment.comment_date}}</div>
        <p>작성자 : {{ comment.author }}</p>
        <p>{{comment.comment_contents}}</p>
        <a href = "{% url 'delete1' comment_id=comment.id post_id=post_id  %}">삭제</a>
            <hr>
    </div>
    {% empty %}
    <p>댓글이 없습니다.</p>
    {% endfor %}

    <form action="{% url 'comment_write' post_pk=post_id %}" method = "POST">
        {% csrf_token %}
        <input type="text" name="content" placeholder="댓글을 작성해주세요.">
        <input type = "submit" value="Write"/>
            <hr>
    </form>
</align>



    </div>
  </div>
</div>
<hr>
<a href = "{% url 'detail' %}">뒤로가기</a>

{% endblock %}    